### PR TITLE
Add circuitBreakerTimeout parameter

### PR DESCRIPTION
**Pull request by oncletom**
Exposing this setting enables to combine rate limiting and circuit breaker nicely.

cc/ @jcnewell

### CODE REVIEW

**Comment by robinjmurphy** [comment]
@oncletom I was thinking about setting this timeout really high as we don't really see it as a feature of the library. The idea is that you should be able to set a per-request timeout, but I don't really like the idea of an overall timeout imposed by the circuit breaker. I think it returns 'command timeout' after 60s currently. What do you think?

**Comment by oncletom** [comment]
@robinjmurphy yep, the timeout could be set to `Infinity` so setting it would be an opt-in from the user to activate the circuit breaker.

**Comment by robinjmurphy** [comment]
I think the circuit breaker would still be active, it just wouldn't have an overall timeout by default.

If we set it to infinity, would you still want control over it?

**Comment by jcnewell** [comment]
We wouldn't need control over it for our application.

**Comment by robinjmurphy** [comment]
Ok. Are you OK to change this PR to set the timeout to infinity then?

**Comment by oncletom** [comment]
@robinjmurphy yep totally :-)

**Comment by jcnewell** [comment]
I've set DEFAULT_CIRCUIT_BREAKER_TIMEOUT to 0x7FFFFFFF as this is the largest value accepted by the setTimeout function.

**Comment by robinjmurphy** [comment]
Cool. Is it worth a comment? Something like 'Set high to effectively disable the circuit breaker timeout'?

**Comment by jcnewell** [comment]
Good point - done.

**Comment by robinjmurphy** [comment]
Thanks @jcnewell

**Pull request merged**
