### PR TITLE
Bring getStatsName into the Client object fixes #68

### LINKED ISSUE #68: Cache Misses and Hits don't include feed name
**Description**
It's great that we can override the name of our client on a per-request basis.
This enables us to have a single-configured client which we can use for multiple feeds. However we do wish to monitor the cache-hits and misses of each individual feed, and it seems currently flashheart doesn't allow that.

**Problem**
When it comes to the cachingClient, the feedname isn't taken into account.
I've added a PR (attached) which fixes that, here is an example..

```
http.cache.misses
GET https://navigation.api.bbci.co.uk/api 200 147 ms
http.Orbit.requests
http.Orbit.responses.200
http.Orbit.response_time 147
http.Orbit.attempts 1
http.cache.misses
GET https://radio-nav-service.api.bbci.co.uk/radio-nav-service/json 200 414 ms
http.RadioNavService.requests
http.RadioNavService.responses.200
http.RadioNavService.response_time 414
http.RadioNavService.attempts 1
http.cache.hits
http.cache.hits
```

You can see that cache.hits and cache.misses don't include the feed name, so i can't tell here whether its RadioNavService or Orbit which is hitting the cache

### PR DESCRIPTION
**Pull request by Jayflux**
Before fix
```
http.cache.misses
GET https://navigation.api.bbci.co.uk/api 200 147 ms
http.Orbit.requests
http.Orbit.responses.200
http.Orbit.response_time 147
http.Orbit.attempts 1
http.cache.misses
GET https://radio-nav-service.api.bbci.co.uk/radio-nav-service/json 200 414 ms
http.RadioNavService.requests
http.RadioNavService.responses.200
http.RadioNavService.response_time 414
http.RadioNavService.attempts 1
http.cache.hits
http.cache.hits

```

After fix

```
http.Orbit.cache.misses
GET https://navigation.api.bbci.co.uk/api 200 298 ms
http.Orbit.requests
http.Orbit.responses.200
http.Orbit.response_time 298
http.Orbit.attempts 1
http.RadioNavService.cache.misses
GET https://radio-nav-service.api.bbci.co.uk/radio-nav-service/json 200 756 ms
http.RadioNavService.requests
http.RadioNavService.responses.200
http.RadioNavService.response_time 756
http.RadioNavService.attempts 1
http.Orbit.cache.hits
http.RadioNavService.cache.hits
```

This fixes #68

### CODE REVIEW

**Comment by DaMouse404** [comment]
One thing to note is that you can pass `name` into `createClient`. This defaults to `http` which is what you're seeing in those stats which is probably a better place to put the names you're showing. 

Otherwise this seems like a really good improvement as we use the both the client `name` and per feed `name` when accessing iBL. Could you add tests for the behaviour that was missing?

**Comment by Jayflux** [comment]
@DaMouse404 yup, i did mention that in the description here https://github.com/bbc/flashheart/issues/68
that doesn't really solve the problem in this case though, as we only want to use 1 client for different end points.

**Comment by DaMouse404** [comment]
It's worth noting that using a single client for multiple APIs means that if a single API fails and triggers the [circuit breaker](https://github.com/bbc/flashheart#circuit-breaker) you won't get any more HTTP requests to any of your APIs rather than just the one that triggered the circuit breaker.

**Comment by Jayflux** [comment]
Yup good point we may need to rethink that on our side

**Comment by Jayflux** [comment]
@DaMouse404 are you still interested in accepting this?

**Comment by DaMouse404** [comment]
@Jayflux, I think this is definitely something we should get merged. At the moment the tests aren't passing in older versions of Node though.

Also, I think it'd be better to create a test like this:
https://github.com/bbc/flashheart/blob/master/test/caching.js#L328-L335

As that tests the actual behaviour you're wanting rather than the internals.

**Comment by nspragg** [comment]
@Jayflux - can you fix the build please? This PR has been open too long. We should either fix it or close it.

**Comment by Jayflux** [comment]
Looking into this now

**Comment by Jayflux** [comment]
@nspragg @DaMouse404 hows that?

**Comment by DaMouse404** [comment]
@Jayflux, I don't know whether you want to look at improving the test slightly? Something along the lines of the other stats tests?
https://github.com/bbc/flashheart/blob/master/test/caching.js#L328-L335

**Comment by Jayflux** [comment]
@DaMouse404 updated

**Comment by nspragg** [comment]
@Jayflux - released in v2.8.5

**Comment by Jayflux** [comment]
Thanks guys!

**Pull request merged**
