### PR TITLE
Copied the shared execution implementation from the fork by @drpacman

### PR DESCRIPTION
**Pull request by MamathaNair**
Copied the shared execution implementation from the fork by @drpacman. We have tested it in one of our services locally and on different versions of Node(for all versions on which the Travis CI build runs tests). Haven't copied the stale while revalidate code as we feel it needs to be revisited.

### CODE REVIEW

**Comment by robinjmurphy** [comment]
Hi @MamathaNair. We've been a bit slow taking a look at the original PR but will take a look tomorrow.

We just need to have a think about whether the shared execution logic belongs inside the client or whether it would be better off as a separate module.

**Comment by MamathaNair** [comment]
Thanks @robinjmurphy

**Comment by nspragg** [comment]
This is a good idea. However, we think it should be a separate module (wrapper). We also recommend making it more generic i.e works for any async function. 

Here is an example that we came up with:
https://gist.github.com/cejast/584b5db48aabeae6e8882e9fa57e873d

**Comment by nspragg** [comment]
Closing PR - happy to reopen if you wish to discuss further.

**Comment by MamathaNair** [comment]
Thanks for your feedback. We are moving the shared execution to a new library.

**Pull request closed without merging**
